# Copyright 2018 SAS Institute Inc.
#
# This work is licensed under a Creative Commons Attribution 4.0
# International License. You may obtain a copy of the License at
# https://creativecommons.org/licenses/by/4.0/.
- type: replace
  path: /instance_groups/name=postgresql/properties/postgres/config?/port
  value: ((db.postgres.port))

- type: replace
  path: /instance_groups/name=pgpool/properties/pgpool/config?/port
  value: ((db.pgpool.port))
