- type: replace
  path: /instance_groups/name=postgresql/properties/postgres/config?/port
  value: ((db.postgres.port))

- type: replace
  path: /instance_groups/name=pgpool/properties/pgpool/config?/port
  value: ((db.pgpool.port))
