#!/bin/bash

set -ue

exit_code=0
GREEN='\033[0;32m'
LIGHT_GREEN='\033[0;92m'
RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
YELLOW='\033[0;93m'
NOCOLOR='\033[0m'

# suite_name should be defined by each of our test suite functions
echo -e "${LIGHT_GREEN} ***** Begin viya-3.3/bosh-cli-v2 tests ***** ${NOCOLOR}"
source viya-3.3/bosh-cli-v2/scripts/test

exit $exit_code
