#!/bin/bash

# This script is a derivative work and based on those included in
# https://github.com/cloudfoundry/cf-deployment/blob/master/scripts/test. The
# following text is the NOTICE file content for that project.
#
# cf-deployment
#
# Copyright (c) 2016-Present CloudFoundry.org Foundation, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ue

exit_code=0
GREEN='\033[0;32m'
LIGHT_GREEN='\033[0;92m'
RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
YELLOW='\033[0;93m'
NOCOLOR='\033[0m'

# suite_name should be defined by each of our test suite functions
echo -e "${LIGHT_GREEN} ***** Begin viya-3.3/bosh-cli-v2 tests ***** ${NOCOLOR}"
source viya-3.3/bosh-cli-v2/scripts/test

exit $exit_code
